#!/bin/sh
echo "Hello from initramfs!"

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev



dd if=/dev/zero of=/dev/fb0 bs=4 count=1000 \
  conv=notrunc status=none



ls /dev 
exec setsid sh -c 'exec sh </dev/ttyAMA0 >/dev/ttyAMA0 2>&1'
